[metadata]
creation_date = "2025/01/28"
integration = []
maturity = "production"
updated_date = "2025/01/28"

[rule]
actions = []
author = ["3727848238"]
description = "Test - SA - Weekly"
enabled = true
exceptions_list = []
false_positives = []
filters = []
from = "now-360s"
index = [
    "apm-*-transaction*",
    "auditbeat-*",
    "endgame-*",
    "filebeat-*",
    "logs-*",
    "packetbeat-*",
    "traces-apm*",
    "winlogbeat-*",
    "-*elastic-cloud-logs-*",
]
interval = "5m"
language = "eql"
license = ""
max_signals = 100
name = "Test - SA - Weekly"
references = []
related_integrations = []
required_fields = []
risk_score = 21
risk_score_mapping = []
rule_id = "89b5d4c2-58b9-4da1-beb7-c2ff880a0ff2"
setup = ""
severity = "low"
severity_mapping = []
tags = []
threat = []
to = "now"
type = "eql"

query = '''
sequence by user.name
      	[authentication where event.action == "login-success"]
      	[authentication where event.action == "login-failed"]
      	until [authentication where event.action == "account-locked"]
'''



[rule.meta]
from = "1m"
kibana_siem_app_url = "https://fmaussion-customer-test.kb.europe-west3.gcp.cloud.es.io:9243/app/security"

